export const DEFAULT_SETTINGS = {
  fontSize: 14,
  fontFamily: "JetBrains Mono, Consolas, Courier New, monospace",
  tabSize: 2,
  wordWrap: "off" as const,
  minimap: true,
  lineNumbers: "on" as const,
  accentColor: "#d4a039",
  activeTheme: "oscura-midnight",
  terminalShell: "",
  terminalFontSize: 13,
  autoSave: "off" as const,
  autoSaveDelay: 1000,
  defaultTerminalCwd: "",
  zenEditorMode: "unified" as const,
  autoLoadLastProject: false,
  particleDensity: 80,
  particleSpeed: 1,
  particleLifespan: 2,
  glassBlur: 20,
  reduceMotion: false,
  particleColor: "",
  glowColor: "",
};

export const KEYBOARD_SHORTCUTS = {
  save: "Ctrl+S",
  openFile: "Ctrl+O",
  openFolder: "Ctrl+Shift+O",
  split: "Ctrl+\\",
  closeTab: "Ctrl+W",
  search: "Ctrl+Shift+F",
  toggleSidebar: "Ctrl+B",
  commandPalette: "Ctrl+Shift+P",
  nextTab: "Ctrl+Tab",
  prevTab: "Ctrl+Shift+Tab",
  toggleZenMode: "Ctrl+Shift+T",
} as const;
